### ISSUE TITLE
Add instructions to deploy Permissioning Dapp to IPFS

### ISSUE THREAD

**Issue by eum602** [ConsenSys/permissioning-smart-contracts#202]
It could be useful to also add instructions how to configure the package.json in order to successfully deploy the permissioning Dapp to IPFS.
For that purpose the following steps can be taken:
*  clone the repository
* Add the following line into the package.json
```shell
"homepage": ".",
```
* Execute: yarn run build ==> **build** directory is created
* Use a preferred option like <a href="https://pinata.cloud/">pinata</a> in order to upload the **build** directory ==> Copy the **hash** related to the uploaded files
* Finally visit the uploaded static web page hosted by IPFS by visiting https://gateway.pinata.cloud/ipfs/<**hash**>/

**Comment by vmichalik** [comment]
Hey @eum602, sorry for the super delayed response to this. 

I think it's a cool idea, though I think rather than docs, unless/until it becomes a more common pattern in our community - I think if you wanted to write it up with some screenshots, it would be a fun little demo/tutorial though we could link in [Awesome Quorum](https://github.com/ConsenSys/awesome-quorum).

If you're still interested, let's chat!

**Comment by eum602** [comment]
Hi @vmichalik sure!!, let me know what are the next steps :)

**Comment by vmichalik** [comment]
Join us over in the Quorum General channel at the ConsenSys Discord, we can chat there! https://discord.gg/hYpHRjK
